package com.se.board.domain.post;

public enum EsSearchHitStage {
//	TITLE, TITLE_AUTHOR, TITLE_WRITER, TITLE_WRITER_CONTENT, CHOSUNG, ENG_TO_HAN, HAN_TO_ENG, NO_RESULT;
	TITLE, TITLE_WRITER, TITLE_WRITER_CONTENT, TITLE_CONTENT, FC, EN_TO_KO, KO_TO_EN, NO_RESULT;
}
